MyCloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('mainapp.urls', namespace='mainapp')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('create-folder/', views.create_new_folder, name='create_new_folder'),
    path('folder/<str:pk>/', views.open_folder, name='open_folder'),
    path('upload_new_file/', views.upload_file, name='upload_file'),
    path('delete_file/', views.delete_file, name='delete_file'),
    path('delete_folder/<str:pk>', views.delete_folder, name='delete_folder')
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
import shutil

# Create your models here.
def get_file_location(instance, filename):
    current_location = instance.folder
    path = ""
    while (current_location):
        path = f'/{current_location.name}' + path
        current_location = current_location.folder
    return f"files/{instance.folder.user.username}/{path}/{filename}"

def get_current_location(current_folder):
    username = current_folder.user.username
    path = ""
    while(current_folder):
        path = f"/{current_folder.name}" + path
        current_folder = current_folder.folder
    return f"media/files/{username}{path}"

class Folder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='folders')
    name = models.CharField(max_length=200)
    folder = models.ForeignKey('self',on_delete=models.CASCADE, related_name='folders_within', null=True)

    def __str__(self):
        return f"{self.user} - {self.name}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['folder', 'name'], name='unique_folder_name'),
            models.UniqueConstraint(fields=['name', 'user'], condition=Q(folder=None), name='unique_folder_on_home_page')
        ] 

    def delete(self, *args, **kwargs):
        try:
           shutil.rmtree(get_current_location(self))
        except:
           pass
        finally:
           super().delete(*args, **kwargs)
        

          

class File(models.Model):
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE, null=True, related_name='files')
    files = models.FileField(upload_to=get_file_location)
    filename= models.CharField(max_length=50, blank=True)

    def __str__(self):
        return f"{self.files}"

    def save(self, *args, **kwargs):
        self.filename = self.files.name
        super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        self.files.storage.delete(self.files.name)
        super().delete(*args, **kwargs)

mainapp/forms.py
from django import forms 
from .models import Folder

class NewFolderForm(forms.ModelForm):
    class Meta:
        model = Folder
        fields = ('name',)

mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import NewFolderForm
from .models import Folder, File
from django.contrib import messages
from django.db import IntegrityError
from django.http import JsonResponse
from http import HTTPStatus

# Create your views here.
@login_required
def home(request):
    folders = request.user.folders.filter(folder=None)
    return redirect('mainapp:open_folder', pk=folders[0].pk)

def create_new_folder(request):
    if request.method=='POST':
        if request.session['redirected_from'] is None:
            messages.error(request, 'Folder not created')
            return redirect('mainapp:home')
        
        # POST request
        form = NewFolderForm(request.POST)

        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user #current logged in user
            redirected_from = request.session['redirected_from'].split('/')
            if redirected_from[3] != '': #create new folder inside another folder
                pk =redirected_from[-2]
                form.folder = get_object_or_404(Folder, pk=pk)
            try:
                form.save()
            except IntegrityError:
                messages.error(request, 'Folder already exists')
            return HttpResponseRedirect(request.session['redirected_from'])
    else:
        # GET request
        request.session['redirected_from'] = request.META.get('HTTP_REFERER')
        createfolder = NewFolderForm()
    return render(request, 'createNewFolder.html',{
        'createfolder': createfolder
    })

def open_folder(request, pk):
    try:
        folder = get_object_or_404(Folder, pk=pk)
    except:
        messages.error(request, 'Folder does not exist')
        return redirect('mainapp:home')
    return render(request, 'openFolder.html', {
        'folder': folder
    })


def upload_file(request):
    # 1. get file from request
    uploaded_file = request.FILES.get('uploadfile')
    # 2.  get folder - folder id
    folder_id = request.POST.get('fid')
    # 3. create new file object
    folder = get_object_or_404(Folder, pk=folder_id)
    File.objects.create(folder=folder, files=uploaded_file)
    # 4. redirect to openfilder.html with folderid
    return redirect('mainapp:open_folder', pk=folder_id)

def delete_file(request):
    pk = request.GET.get('pk')
    user = request.GET.get('user')

    try:
        if request.user.username != user:
            raise Exception('Unauthorized User')
        delfile = get_object_or_404(File, pk=pk)
        delfile.delete()
        return JsonResponse({
            delfile.filename:"Deleted",
            "status": HTTPStatus.OK
        })
    except Exception as e:
        return JsonResponse({
            "File": str(e),
            "status": HTTPStatus.NOT_FOUND
        })
    
def delete_folder(request, pk):
    folder = get_object_or_404(Folder, pk=pk)
    try:
        fid = folder.folder.pk
    except:
        return redirect("mainapp:home")
    else:   
        return redirect("mainapp:open_folder", pk=fid)
    finally:
        folder.delete()
    

mainapp/templates/createNewFolder.html
{% extends 'base.html'%}

{% block content %}
    <form method="POST">
        {% csrf_token%}
        {{createfolder.as_p}}
        <input type="submit" value="Create Folder">
    </form>
{% endblock content %}

mainapp/templates/home.html
{% extends 'base.html'%}
{% block content %}
    <br>
    <a href="{% url 'mainapp:create_new_folder' %}">Create New Folder</a>
    <br>
    {% for folder in folders %}
        <a href="{% url 'mainapp:open_folder' folder.pk %}">{{folder.name|linebreaks}}</a>
    {% endfor %}
{% endblock content %}

mainapp/templates/openFolder.html
{% extends 'base.html'%}

{% block content %}
    
    <a href="{% url 'mainapp:create_new_folder' %}">Create folder</a>
    <br>
    {% include "upload_file.html" %}
    <br>
    {% if folder.folder %}  
    <form action="{% url 'mainapp:delete_folder' folder.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
    {% endif %}
    {% for folder in folder.folders_within.all %}
        <a href="{% url 'mainapp:open_folder' folder.pk %}">{{folder|linebreaks}}</a>
    {% endfor %}
    {% for file in folder.files.all %}
        <div>
            <a href="{{file.files.url}}">{{file.filename}}</a> - <button onclick="delfile(this.id)" class="button" id="{{file.pk}}">Delete</button> <br>
        </div>   
    {% endfor %}
{% endblock content %}

{% block script %}

    <script>
        function delfile(del_file_id){
            fetch(`{% url 'mainapp:delete_file' %}?pk=${del_file_id}&user={{request.user}}`, {
                method:'POST',
                headers:{'X-CSRFToken':"{{csrf_token}}"}
            }).then(response=>response.json()).then(data=>{
                console.log(data)
                if (data.status==200){
                    file = document.getElementById(del_file_id).parentElement.remove()
                }
            }) 
        }
    </script>
{% endblock script %}

mainapp/templates/upload_file.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Upload File
  </button>
  
  <!-- Modal -->
  <form method="POST" enctype="multipart/form-data" action="{% url 'mainapp:upload_file' %}">
    {% csrf_token %}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Upload File</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="file" name="uploadfile">
                <input type="hidden" name="fid" value="{{folder.pk}}">
            </div>
            <div class="modal-footer">
                    <input type="submit" value="Upload">
            </div>
          </div>
        </div>
    </div>
  </form>
  