MyCloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('mainapp.urls', namespace='mainapp')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('login/', views.user_login, name='login'),
    # path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <title>base</title>
</head>
<script type="text/javascript" language="javascript"></script>
<body>
    {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:profile' %}">Ative user: {{request.user}}</a> &nbsp; &nbsp;
    <a href="{% url 'logout' %}">Logout</a><br>
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            {{message}}
        {% endfor %}
    {% endif %}
    {% block content%}{% endblock content%}
</body>
{% block script %}
  
{% endblock script %}
</html>